### ISSUE TITLE
Error when importing RandomForestQuantileRegressor on windows python 3.9.9

### ISSUE THREAD

**Issue by moeinfinityx** [zillow/quantile-forest#1]
## Platform:

Windows x64

Python version: 3.9.9

## Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\venv\lib\site-packages\quantile_forest\__init__.py", line 3, in <module>
    from ._quantile_forest import ExtraTreesQuantileRegressor
  File "...\venv\lib\site-packages\quantile_forest\_quantile_forest.py", line 42, in <module>
    from ._quantile_forest_fast import QuantileForest
  File "quantile_forest\\_quantile_forest_fast.pyx", line 1, in init quantile_forest._quantile_forest_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

## How to Replica

```
pip install quantile-forest
python
>>> from quantile_forest import RandomForestQuantileRegressor
```

and it will raise the error.

Also, would you mind provide build for python 3.10 on windows?

**Comment by reidjohnson** [comment]
Thanks for the issue.

What version of NumPy are you using? Please ensure it's up to date (i.e., `pip install --upgrade numpy`). The error can be the result of a known issue with select versions of NumPy (thread [here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)).

We'll look into providing a Python 3.10 build for Windows. There are currently some issues that cause a build failure with that configuration that need to be resolved first.

**Comment by moeinfinityx** [comment]
I was using numpy 1.21.5, which is the default one when installing from conda. After upgrading it to 1.22.3 problem solved. Thanks for your help :)

**Comment by reidjohnson** [comment]
Glad to hear it! Thanks for following up with confirmation.

**Comment by reidjohnson** [comment]
Following up here that Python 3.10/3.11 builds for Windows (64-bit) are now supported.
